import test from 'node:test';import assert from 'node:assert/strict';
import {buildReport,reportExport,reportDay} from '../web/report-engine.js';
const data={products:[{id:1,name:'A',category:'Salud',stock:7,stock_enabled:true,stock_min:8,stock_max:20,average_cost:10},{id:2,name:'B',category:'Salud',stock:0,stock_enabled:false}],stores:[{id:1}],orders:[{id:'o1',store_id:1,store_name:'Tienda',agent_id:2,agent_name:'Agente',captured_at:'2026-10-02T02:00:00Z',commercial_status:'entregado',items:[{product_id:1,product_name:'A',quantity:2,unit_price:20},{product_id:2,product_name:'B',quantity:5,unit_price:30}]}],report_movements:[{event_id:1,product_id:1,delta:10,created_at:'2026-09-01T12:00:00Z',reason:'compra_proveedor',supplier_id:4,unit_cost:10},{event_id:2,product_id:1,delta:-3,created_at:'2026-10-01T12:00:00Z',kind:'despacho'}]};
test('Filtro producto no suma otras líneas del pedido y usa fecha Colombia',()=>{const r=buildReport(data,{type:'orders',product:'1',from:'2026-10-01',to:'2026-10-01'});assert.equal(r.records.length,1);assert.equal(r.totals.at(-1)[1],40);assert.equal(reportDay(data.orders[0].captured_at),'2026-10-01');assert.equal(buildReport(data,{type:'orders',store:'999'}).records.length,0);});
test('Kardex filtrado conserva saldo anterior al período',()=>{const r=buildReport(data,{type:'movements',from:'2026-10-01'});assert.equal(r.records.length,1);assert.equal(r.records[0].cells[9],10);assert.equal(r.records[0].cells[10],7);});
test('Agotados no incluye productos sin registrar; mínimos y proveedor filtran',()=>{assert.equal(buildReport(data,{type:'inventory',stock:'empty'}).records.length,0);assert.equal(buildReport(data,{type:'inventory',stock:'low'}).records.length,1);assert.equal(buildReport(data,{type:'purchases',supplier:'4'}).records.length,1);assert.equal(buildReport(data,{type:'purchases',supplier:'8'}).records.length,0);});
test('Exportación conserva todas las filas y no trunca en 200 movimientos',()=>{const d={...data,report_movements:Array.from({length:220},(_,i)=>({...data.report_movements[0],event_id:i+1,delta:1}))},r=buildReport(d,{type:'movements'});assert.equal(r.records.length,220);assert.deepEqual(reportExport(r,{}).slice(-220),r.records.map(r=>r.cells));});
test('Cancelados y revisión no inflan total de pedidos',()=>{for(const patch of [{commercial_status:'cancelado'},{status:'revision'}]){const r=buildReport({...data,orders:[{...data.orders[0],...patch}]},{type:'orders'});assert.equal(r.totals.at(-1)[1],0);}});
test('Devoluciones y neto respetan el producto seleccionado',()=>{const order={...data.orders[0],returns:[{items:[{product_id:1,quantity:1},{product_id:2,quantity:2}]}]};const r=buildReport({...data,orders:[order]},{type:'orders',product:'1'});assert.equal(r.totals.at(-2)[1],20);assert.equal(r.totals.at(-1)[1],20);});
