import {favorites,toggleFavorite} from './favorites.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(v);
const placeholder='<div class="public-placeholder"><span aria-hidden="true">✚</span>Imagen no disponible</div>';
let products=[],page=1,loaded=false,favoritesOnly=false;const pageSize=12;
function art(p){let url='';try{const parsed=new URL(p.image_url,location.origin);if(parsed.protocol==='https:'||parsed.origin===location.origin)url=parsed.href;}catch{}return p.image_valid&&p.image_url&&url?`<img src="${esc(url)}" alt="${esc(p.name)}" loading="lazy">`:placeholder;}
function bindImages(root){root.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.parentElement.innerHTML=placeholder;},{once:true}));}
function render(){
 if(!loaded)return;
 const term=$('#search').value.trim().toLocaleLowerCase('es');let rows=products.filter(p=>(!favoritesOnly||favorites().has(p.id))&&(p.name+' '+p.description).toLocaleLowerCase('es').includes(term)&&(!$('#category').value||p.category===$('#category').value)&&(!$('#manufacturer').value||p.manufacturer_name===$('#manufacturer').value));
 rows.sort((a,b)=>$('#sort').value==='price-up'?a.price-b.price:$('#sort').value==='price-down'?b.price-a.price:a.name.localeCompare(b.name,'es'));
 const pages=Math.max(1,Math.ceil(rows.length/pageSize));page=Math.min(page,pages);$('#status').textContent=`${rows.length} producto${rows.length===1?'':'s'} disponible${rows.length===1?'':'s'}`;
 $('#products').innerHTML=rows.slice((page-1)*pageSize,page*pageSize).map(p=>`<article class="public-product"><div class="public-art">${art(p)}</div><div class="public-product-body"><span class="eyebrow green">${esc(p.category||'General')}</span><h2>${esc(p.name)}</h2><p>${esc(p.manufacturer_name)}</p><strong class="public-price">${money(p.price)}</strong><p class="note">${p.discount_percent?`${p.discount_percent}% desde ${p.discount_min} unidades`: ''}</p><button class="button secondary favorite-button" data-favorite="${p.id}" aria-pressed="${favorites().has(p.id)}">${favorites().has(p.id)?'★ Quitar favorito':'☆ Guardar favorito'}</button><button class="button secondary" data-product="${p.id}">Ver detalles</button></div></article>`).join('')||'<div class="public-empty"><h2>No encontramos productos</h2><p>Prueba con otra búsqueda o cambia los filtros.</p></div>';
 $('#pagination').innerHTML=pages>1?`<button class="button secondary" data-page="${page-1}" ${page===1?'disabled':''}>Anterior</button><span>Página ${page} de ${pages}</span><button class="button secondary" data-page="${page+1}" ${page===pages?'disabled':''}>Siguiente</button>`:'';bindImages($('#products'));
}
async function load(){
 loaded=false;$('#status').textContent='Cargando productos…';$('#products').replaceChildren();$('#pagination').replaceChildren();$('#filters').inert=true;
 try{const res=await fetch('/api/public/products',{credentials:'omit',cache:'no-store',signal:AbortSignal.timeout(15000)});if(!res.ok)throw Object.assign(new Error(),{status:res.status});const data=await res.json();if(!Array.isArray(data.products))throw Error();products=data.products;loaded=true;
 for(const [id,field,label] of [['category','category','Todas las categorías'],['manufacturer','manufacturer_name','Todos los fabricantes']]){const select=$('#'+id);select.innerHTML=`<option value="">${label}</option>`+[...new Set(products.map(p=>p[field]).filter(Boolean))].sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}page=1;render();
 }catch(error){loaded=false;const message=[401,404].includes(error.status)?'El servidor necesita actualizarse. Reinicia PharmaBoost y vuelve a intentarlo.':'No pudimos cargar el catálogo. Comprueba tu conexión e inténtalo de nuevo.';$('#status').innerHTML=`<div class="public-error">${message} <button class="button secondary" id="retry">Reintentar</button></div>`;$('#retry').addEventListener('click',load);}finally{$('#filters').inert=!loaded;}
}
$('#filters').addEventListener('submit',e=>e.preventDefault());$('#search').addEventListener('input',()=>{page=1;render();});for(const id of ['category','manufacturer','sort'])$('#'+id).addEventListener('change',()=>{page=1;render();});
$('#pagination').addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b){page=Number(b.dataset.page);render();$('#status').scrollIntoView({block:'start'});}});
$('#products').addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){try{toggleFavorite(Number(fav.dataset.favorite));render();}catch{$('#status').textContent='Permite el almacenamiento local para guardar favoritos.';}return;}const b=e.target.closest('[data-product]');if(!b)return;const p=products.find(p=>p.id===Number(b.dataset.product));if(!p)return;$('#detail').innerHTML=`<button class="button secondary detail-close" type="button">Cerrar</button><p class="eyebrow green">${esc(p.category||'General')}</p><h2 id="detail-title">${esc(p.name)}</h2><div class="public-art">${art(p)}</div><p>${esc(p.description)}</p><p>Fabricante: <strong>${esc(p.manufacturer_name)}</strong></p><strong class="public-price">${money(p.price)}</strong><p class="note">Para gestionar pedidos, ingresa con una cuenta autorizada.</p><a class="button primary" href="/">Iniciar sesión</a>`;$('#detail .detail-close').addEventListener('click',()=>$('#detail').close());bindImages($('#detail'));$('#detail').showModal();});
const favoriteFilter=document.createElement('button');favoriteFilter.type='button';favoriteFilter.className='button secondary';favoriteFilter.textContent='Ver favoritos';favoriteFilter.setAttribute('aria-pressed','false');$('#filters').after(favoriteFilter);favoriteFilter.addEventListener('click',()=>{favoritesOnly=!favoritesOnly;favoriteFilter.textContent=favoritesOnly?'Ver todos los productos':'Ver favoritos';favoriteFilter.setAttribute('aria-pressed',String(favoritesOnly));page=1;render();});
load();
window.addEventListener('offline',()=>{products=[];loaded=false;$('#products').replaceChildren();$('#pagination').replaceChildren();$('#filters').inert=true;$('#detail').close();$('#status').textContent='Conexión requerida para consultar el catálogo.';});
window.addEventListener('online',load);
