export const reportTypes={general:'Resumen general',orders:'Pedidos por tienda y producto',inventory:'Inventario general',movements:'Kardex de movimientos',purchases:'Compras por proveedor'};
export function reportDay(value){const n=Date.parse(value);return Number.isFinite(n)?new Date(n-5*3600000).toISOString().slice(0,10):String(value||'').slice(0,10);}
export function buildReport(data,f={}){
 const eq=(value,filter)=>!filter||String(value)===String(filter),query=String(f.search||'').toLocaleLowerCase('es'),match=values=>values.join(' ').toLocaleLowerCase('es').includes(query);
 const inRange=v=>(!f.from||reportDay(v)>=f.from)&&(!f.to||reportDay(v)<=f.to);
 const products=data.products||[],lookup=new Map(products.map(p=>[p.id,p]));
 const ps=products.filter(p=>eq(p.id,f.product)&&eq(p.category,f.category));
 const stockMatch=p=>!f.stock||(f.stock==='available'&&p.stock_enabled&&p.stock>0)||(f.stock==='empty'&&p.stock_enabled&&p.stock===0)||(f.stock==='low'&&p.stock_enabled&&p.stock<p.stock_min)||(f.stock==='high'&&p.stock_enabled&&p.stock_max>0&&p.stock>p.stock_max)||(f.stock==='unknown'&&!p.stock_enabled);
 const inventory=ps.filter(p=>stockMatch(p)&&match([p.name,p.external_code,p.category]));
 let orders=(data.orders||[]).filter(o=>inRange(o.captured_at)&&eq(o.store_id,f.store)&&eq(o.agent_id,f.agent)&&eq(o.promotion_id,f.promotion)&&eq(o.commercial_status,f.status));
 const orderRows=[];let returnedValue=0;let orderValue=0;const counted=new Set(),clients=new Set();
 for(const o of orders)for(const i of o.items||[]){const p=lookup.get(i.product_id);if(!eq(i.product_id,f.product)||!eq(p?.category,f.category)||!match([o.id,o.store_name,o.agent_name,i.product_name,o.notes]))continue;
  const included=o.commercial_status!=='cancelado'&&o.status!=='revision',subtotal=i.quantity*i.unit_price;
  if(included){orderValue+=subtotal;returnedValue+=(o.returns||[]).reduce((s,r)=>s+(r.items||[]).filter(x=>x.product_id===i.product_id).reduce((a,x)=>a+x.quantity*i.unit_price,0),0);counted.add(o.id);clients.add(o.store_id);}
  orderRows.push({name:i.product_name,date:o.captured_at,value:subtotal,detail:o.id,cells:[reportDay(o.captured_at),o.id,o.store_name,o.agent_name,i.product_name,i.quantity,i.unit_price,subtotal,o.status==='revision'?'En revisión':o.commercial_status]});
 }
 const balances=new Map();const ledger=[...(data.report_movements||[])].sort((a,b)=>a.event_id-b.event_id).map(r=>{const before=balances.get(r.product_id)||0,after=before+r.delta;balances.set(r.product_id,after);return {...r,before,after};});
 const movements=ledger.filter(r=>inRange(r.created_at)&&eq(r.product_id,f.product)&&eq(r.supplier_id,f.supplier)&&eq(r.user_id,f.agent)&&eq(lookup.get(r.product_id)?.category,f.category)&&match([lookup.get(r.product_id)?.name,r.note,r.invoice,r.supplier,r.actor]));
 const purchases=movements.filter(r=>r.reason==='compra_proveedor'&&r.delta>0);
 let headers,records;const type=f.type||'general';
 if(type==='orders'){headers=['Fecha Colombia','Pedido','Tienda cliente','Agente','Producto','Cantidad','Precio COP','Subtotal COP','Estado'];records=orderRows;}
 else if(type==='inventory'||type==='general'){headers=['Producto','Código','Categoría','Unidad de venta','Existencias','Mínimo','Máximo sugerido','Costo promedio COP','Valor stock COP'];records=inventory.map(p=>({name:p.name,value:p.stock*(p.average_cost||0),detail:p.id,cells:[p.name,p.external_code,p.category,p.unit||'unidad',p.stock_enabled?p.stock:'Sin registrar',p.stock_min||0,p.stock_max||'Sin definir',p.average_cost??'Sin valorar',p.stock_enabled&&p.average_cost!=null?Math.round(p.stock*p.average_cost*100)/100:'Sin valorar']}));}
 else {const buying=type==='purchases';headers=['Fecha Colombia','Movimiento','Producto','Unidad','Tipo / motivo','Proveedor','Factura referencia','Entrada','Salida','Saldo anterior','Saldo posterior','Costo compra COP','Valor compra COP','Registrado por'];records=(buying?purchases:movements).map(r=>({name:lookup.get(r.product_id)?.name||String(r.product_id),date:r.created_at,value:r.delta>0&&r.unit_cost!=null?r.delta*r.unit_cost:0,detail:r.event_id,cells:[reportDay(r.created_at),r.event_id,lookup.get(r.product_id)?.name||r.product_id,r.unit||'unidad',r.reason||r.kind,r.supplier||'',r.invoice||'',Math.max(0,r.delta),Math.max(0,-r.delta),r.before,r.after,r.unit_cost??'',r.delta>0&&r.unit_cost!=null?Math.round(r.delta*r.unit_cost*100)/100:'',r.actor||'']}));}
 records.sort((a,b)=>f.sort==='value'?b.value-a.value:f.sort==='date'?String(b.date||'').localeCompare(String(a.date||'')):String(a.name||'').localeCompare(String(b.name||''),'es'));
 const valued=inventory.filter(p=>p.stock_enabled&&p.average_cost!=null),totalCost=purchases.reduce((s,r)=>s+(r.unit_cost==null?0:r.delta*r.unit_cost),0);
 const totals=type==='orders'?[['Pedidos contabilizados',counted.size],['Tiendas con pedidos',clients.size],['Valor pedidos COP',orderValue],['Devoluciones COP',returnedValue],['Valor neto pedidos COP',orderValue-returnedValue]]:type==='movements'||type==='purchases'?[['Movimientos',records.length],['Movimientos de entrada',(type==='purchases'?purchases:movements).filter(r=>r.delta>0).length],['Movimientos de salida',(type==='purchases'?purchases:movements).filter(r=>r.delta<0).length],['Valor compras conocido COP',Math.round(totalCost*100)/100],['Compras sin costo',purchases.filter(r=>r.unit_cost==null).length]]:[['Productos',inventory.length],['Tiendas clientes',(data.stores||[]).length],['Productos disponibles',inventory.filter(p=>p.stock_enabled&&p.stock>0).length],['Agotados',inventory.filter(p=>p.stock_enabled&&p.stock===0).length],['Sin inventario registrado',inventory.filter(p=>!p.stock_enabled).length],['Valor stock conocido COP',Math.round(valued.reduce((s,p)=>s+p.stock*p.average_cost,0)*100)/100],['Sin valoración',inventory.filter(p=>p.average_cost==null).length],...(type==='general'?[['Pedidos del período',counted.size],['Valor pedidos del período COP',orderValue],['Devoluciones COP',returnedValue],['Valor neto pedidos COP',orderValue-returnedValue]]:[])];
 const note=type==='orders'?'El total excluye cancelados y pedidos en revisión; distingue el valor original, las devoluciones conocidas de esos pedidos y su neto. La fecha filtra el pedido, no la fecha de devoluciones. Son pedidos comerciales, no facturación ni cobros.':type==='inventory'||type==='general'?'Inventario actual de la última sincronización. Las fechas filtran pedidos del resumen, no reconstruyen existencias históricas. Sin registrar no significa agotado. No se suman unidades de presentaciones distintas.':'Kardex completo de movimientos recibidos, sin límite de 200 filas. Los saldos incluyen movimientos anteriores al período. Las cantidades corresponden a la unidad del producto; no hay conversión entre presentaciones. La referencia de factura es un dato de compra, no una factura emitida por PharmaBoost.';
 return {title:reportTypes[type],headers,records,totals,note};
}
export function reportExport(report,filters){return [[report.title],['Filtros aplicados',typeof filters==='string'?filters:JSON.stringify(filters)],...report.totals,[],[report.note],[],report.headers,...report.records.map(r=>r.cells)];}
